-- MySQL Script generated by MySQL Workbench
-- 04/22/17 23:26:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrator` (
  `account` BIGINT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Organization` (
  `account` BIGINT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `leader` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `establishedTime` DATE NULL,
  `email` VARCHAR(45) NULL,
  `money` DOUBLE NULL,
  PRIMARY KEY (`account`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Individual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Individual` (
  `account` BIGINT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  `ID` VARCHAR(18) NULL,
  `email` VARCHAR(45) NULL,
  `money` DOUBLE NULL,
  PRIMARY KEY (`account`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Task` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `publisher` BIGINT NULL,
  `name` VARCHAR(45) NULL,
  `credit` DOUBLE NULL,
  `startTime` DATE NULL,
  `endTime` DATE NULL,
  `leader` VARCHAR(45) NULL,
  `phone` BIGINT NULL,
  `address` VARCHAR(45) NULL,
  `description` MEDIUMTEXT NULL,
  `process` MEDIUMTEXT NULL,
  `requirement` MEDIUMTEXT NULL,
  `state` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Attend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Attend` (
  `Individual_account` BIGINT NOT NULL,
  `Task_ID` INT NOT NULL,
  `attendTime` DATE NULL,
  PRIMARY KEY (`Individual_account`, `Task_ID`),
  INDEX `fk_Individual_has_Task_Task1_idx` (`Task_ID` ASC),
  INDEX `fk_Individual_has_Task_Individual_idx` (`Individual_account` ASC),
  CONSTRAINT `fk_Individual_has_Task_Individual`
    FOREIGN KEY (`Individual_account`)
    REFERENCES `mydb`.`Individual` (`account`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Individual_has_Task_Task1`
    FOREIGN KEY (`Task_ID`)
    REFERENCES `mydb`.`Task` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
